# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './billing_profile_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formProfileManager(object):
    def setupUi(self, formProfileManager):
        formProfileManager.setObjectName("formProfileManager")
        formProfileManager.resize(806, 416)
        font = QtGui.QFont()
        font.setPointSize(11)
        formProfileManager.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/rabbit.ico"), QtGui.QIcon.Active, QtGui.QIcon.On)
        formProfileManager.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(formProfileManager)
        self.centralwidget.setObjectName("centralwidget")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(230, 360, 80, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnAdd.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon_24x24/icon_24x24/add_24x24.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btnAdd.setIcon(icon1)
        self.btnAdd.setObjectName("btnAdd")
        self.btnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEdit.setGeometry(QtCore.QRect(320, 360, 80, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon_512x512/icon_512x512/edit.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btnEdit.setIcon(icon2)
        self.btnEdit.setObjectName("btnEdit")
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(410, 360, 80, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon_24x24/icon_24x24/trash-circle-red-5121.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btnDelete.setIcon(icon3)
        self.btnDelete.setObjectName("btnDelete")
        self.btnDeleteAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeleteAll.setGeometry(QtCore.QRect(500, 360, 91, 28))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon_24x24/icon_24x24/trash_24x24.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btnDeleteAll.setIcon(icon4)
        self.btnDeleteAll.setObjectName("btnDeleteAll")
        self.tbProfile = QtWidgets.QTableWidget(self.centralwidget)
        self.tbProfile.setGeometry(QtCore.QRect(9, 9, 791, 341))
        self.tbProfile.setRowCount(0)
        self.tbProfile.setColumnCount(2)
        self.tbProfile.setObjectName("tbProfile")
        item = QtWidgets.QTableWidgetItem()
        self.tbProfile.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbProfile.setHorizontalHeaderItem(1, item)
        self.tbProfile.horizontalHeader().setDefaultSectionSize(150)
        self.tbProfile.horizontalHeader().setStretchLastSection(True)
        self.tbProfile.verticalHeader().setVisible(False)
        formProfileManager.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(formProfileManager)
        self.statusbar.setObjectName("statusbar")
        formProfileManager.setStatusBar(self.statusbar)

        self.retranslateUi(formProfileManager)
        self.tbProfile.itemDoubleClicked['QTableWidgetItem*'].connect(self.btnEdit.click)
        QtCore.QMetaObject.connectSlotsByName(formProfileManager)

    def retranslateUi(self, formProfileManager):
        _translate = QtCore.QCoreApplication.translate
        formProfileManager.setWindowTitle(_translate("formProfileManager", "Profile Manager"))
        self.btnAdd.setText(_translate("formProfileManager", "Add"))
        self.btnEdit.setText(_translate("formProfileManager", "Edit"))
        self.btnDelete.setText(_translate("formProfileManager", "Delete"))
        self.btnDeleteAll.setText(_translate("formProfileManager", "Delete All"))
        item = self.tbProfile.horizontalHeaderItem(0)
        item.setText(_translate("formProfileManager", "ID"))
        item = self.tbProfile.horizontalHeaderItem(1)
        item.setText(_translate("formProfileManager", "Profile Name"))
