# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_proxy_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(340, 271)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../images/rabbit.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(170, 240, 166, 28))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 83, 30))
        self.label_4.setIndent(5)
        self.label_4.setObjectName("label_4")
        self.txtName = QtWidgets.QLineEdit(Dialog)
        self.txtName.setGeometry(QtCore.QRect(99, 14, 231, 28))
        self.txtName.setObjectName("txtName")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(9, 13, 54, 30))
        self.label_2.setIndent(5)
        self.label_2.setObjectName("label_2")
        self.txtContent = QtWidgets.QPlainTextEdit(Dialog)
        self.txtContent.setGeometry(QtCore.QRect(100, 60, 231, 161))
        self.txtContent.setObjectName("txtContent")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add new account"))
        self.label_4.setText(_translate("Dialog", "Values"))
        self.txtName.setToolTip(_translate("Dialog", "<html><head/><body><p>Email address</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Name"))
