# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './setting_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formProfileManager(object):
    def setupUi(self, formProfileManager):
        formProfileManager.setObjectName("formProfileManager")
        formProfileManager.resize(526, 380)
        font = QtGui.QFont()
        font.setPointSize(11)
        formProfileManager.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./../../images/rabbit.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        formProfileManager.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(formProfileManager)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 511, 150))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 40, 63, 20))
        self.label.setObjectName("label")
        self.txtWebhook = QtWidgets.QLineEdit(self.groupBox)
        self.txtWebhook.setGeometry(QtCore.QRect(110, 30, 391, 28))
        self.txtWebhook.setObjectName("txtWebhook")
        self.btnBrowerOpened = QtWidgets.QCheckBox(self.groupBox)
        self.btnBrowerOpened.setGeometry(QtCore.QRect(30, 70, 331, 26))
        self.btnBrowerOpened.setObjectName("btnBrowerOpened")
        self.btnOrderPlaced = QtWidgets.QCheckBox(self.groupBox)
        self.btnOrderPlaced.setGeometry(QtCore.QRect(30, 90, 331, 26))
        self.btnOrderPlaced.setObjectName("btnOrderPlaced")
        self.btnPaymentFalse = QtWidgets.QCheckBox(self.groupBox)
        self.btnPaymentFalse.setGeometry(QtCore.QRect(30, 110, 331, 26))
        self.btnPaymentFalse.setObjectName("btnPaymentFalse")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 165, 511, 149))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnDevMode = QtWidgets.QCheckBox(self.groupBox_2)
        self.btnDevMode.setGeometry(QtCore.QRect(30, 100, 341, 26))
        self.btnDevMode.setObjectName("btnDevMode")
        self.btnBrowserPaymentFalse = QtWidgets.QCheckBox(self.groupBox_2)
        self.btnBrowserPaymentFalse.setGeometry(QtCore.QRect(30, 40, 331, 26))
        self.btnBrowserPaymentFalse.setObjectName("btnBrowserPaymentFalse")
        self.btnStopAll = QtWidgets.QCheckBox(self.groupBox_2)
        self.btnStopAll.setGeometry(QtCore.QRect(30, 70, 331, 26))
        self.btnStopAll.setObjectName("btnStopAll")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(160, 320, 84, 28))
        self.btnSave.setObjectName("btnSave")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(260, 320, 84, 28))
        self.btnCancel.setObjectName("btnCancel")
        formProfileManager.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(formProfileManager)
        self.statusbar.setObjectName("statusbar")
        formProfileManager.setStatusBar(self.statusbar)

        self.retranslateUi(formProfileManager)
        QtCore.QMetaObject.connectSlotsByName(formProfileManager)

    def retranslateUi(self, formProfileManager):
        _translate = QtCore.QCoreApplication.translate
        formProfileManager.setWindowTitle(_translate("formProfileManager", "Settings"))
        self.groupBox.setTitle(_translate("formProfileManager", "Notifications"))
        self.label.setText(_translate("formProfileManager", "Webhook"))
        self.btnBrowerOpened.setText(_translate("formProfileManager", "Browser Opened"))
        self.btnOrderPlaced.setText(_translate("formProfileManager", "Order Placed"))
        self.btnPaymentFalse.setText(_translate("formProfileManager", "Payment Failed"))
        self.groupBox_2.setTitle(_translate("formProfileManager", "Generral"))
        self.btnDevMode.setText(_translate("formProfileManager", "Don\'t actual buy items (Used for dev and testing)"))
        self.btnBrowserPaymentFalse.setText(_translate("formProfileManager", "Open browser on payment failed"))
        self.btnStopAll.setText(_translate("formProfileManager", "Stop All after success"))
        self.btnSave.setText(_translate("formProfileManager", "Save"))
        self.btnCancel.setText(_translate("formProfileManager", "Cancel"))
